import test from "node:test";
import assert from "node:assert/strict";
import { once } from "node:events";
import { createAlertConsole } from "./server.js";

async function withServer(fn){const server=createAlertConsole();server.listen(0,"127.0.0.1");await once(server,"listening");try{await fn(`http://127.0.0.1:${server.address().port}`)}finally{server.close();await once(server,"close")}}
const event={eventId:"event-1",dedupKey:"program:authority",mode:"devnet",level:"devnet",cluster:"devnet",subject:{type:"program",id:"Program111"},ruleId:"authority-rule",ruleVersion:1,status:"breach",severity:"high",uncertainty:"single_source",evidenceIds:["evidence-1"],recommendedAction:"Review authority.",occurredAt:"2026-09-26T12:00:00Z",source:{id:"devnet-monitor",type:"monitoring_backend"},slot:123};

test("serves independent white Alert Console and health",async()=>withServer(async base=>{assert.equal((await fetch(`${base}/api/health`)).status,200);const html=await(await fetch(base)).text();assert.match(html,/Kelvara Alert Console/);assert.match(html,/Paper/);assert.match(html,/Monitored Devnet/);assert.match(html,/Monitoring rules/);assert.match(html,/Activate selected/);assert.match(html,/Pause selected/);assert.match(html,/Activate pause alert/);assert.match(html,/Clear fixture alerts/)}));

test("starts empty, activates a manual fixture alert, and clears it",async()=>withServer(async base=>{
 let alerts=await(await fetch(`${base}/api/alerts`)).json();assert.deepEqual(alerts,[]);
 let response=await fetch(`${base}/api/demo/activate/pause`,{method:"POST"});assert.equal(response.status,201);const activated=await response.json();assert.equal(activated.alert.mode,"fixture_simulation");assert.equal(activated.alert.lifecycle,"open");assert.match(activated.alert.solanaMeaning,/real Solana deployment/i);assert.match(activated.alert.solanaMeaning,/paused account state/i);
 alerts=await(await fetch(`${base}/api/alerts?mode=fixture_simulation`)).json();assert.equal(alerts.length,1);
 response=await fetch(`${base}/api/demo/clear`,{method:"POST"});assert.equal(response.status,200);assert.equal((await response.json()).cleared,1);
 assert.deepEqual(await(await fetch(`${base}/api/alerts`)).json(),[])
}));

test("ingests, lists, filters, acknowledges, and resolves alerts",async()=>withServer(async base=>{let response=await fetch(`${base}/api/events`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(event)});assert.equal(response.status,201);const created=await response.json();response=await fetch(`${base}/api/events`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...event,eventId:"event-2"})});assert.equal(response.status,200);let alerts=await(await fetch(`${base}/api/alerts?mode=devnet&lifecycle=open`)).json();assert.equal(alerts.length,1);assert.equal(alerts[0].occurrences,2);response=await fetch(`${base}/api/alerts/${encodeURIComponent(created.alert.id)}/acknowledge`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actor:"analyst"})});assert.equal((await response.json()).lifecycle,"acknowledged");response=await fetch(`${base}/api/alerts/${encodeURIComponent(created.alert.id)}/resolve`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({resolution:"reviewed"})});assert.equal((await response.json()).lifecycle,"resolved")}));

test("exposes SSE alert changes",async()=>withServer(async base=>{const controller=new AbortController();const stream=await fetch(`${base}/api/stream`,{signal:controller.signal});const reader=stream.body.getReader();await reader.read();await fetch(`${base}/api/events`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(event)});const {value}=await reader.read();const text=new TextDecoder().decode(value);assert.match(text,/event: alert/);assert.match(text,/"type":"created"/);await reader.cancel();controller.abort()}));

test("rejects fixture event pretending to be monitored devnet",async()=>withServer(async base=>{const response=await fetch(`${base}/api/events`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...event,source:null})});assert.equal(response.status,400);assert.equal((await response.json()).error,"invalid_alert_input")}));

test("publishes paused rules, activates many, and evaluates monitored evidence",async()=>withServer(async base=>{const rule={id:"nav-ceiling",version:1,name:"NAV ceiling",cluster:"devnet",field:"nav",operator:"greater_than",threshold:1.05,nearThresholdPercent:5,severity:"high",recommendedAction:"Review NAV."};let response=await fetch(`${base}/api/rules`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rule,actor:"rule-studio"})});assert.equal(response.status,201);assert.equal((await response.json()).activation,"paused");response=await fetch(`${base}/api/rules/activate`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rules:[{id:rule.id,version:1}],actor:"analyst"})});assert.equal((await response.json())[0].activation,"active");const evidence={id:"evidence-live",cluster:"devnet",state:"active",freshness:{status:"fresh",ageMs:100},confidence:"verified",coverage:"complete",value:{nav:1.06},source:{id:"monitor",type:"monitoring_backend"},slot:123,observedAt:"2026-09-26T12:00:00Z",fetchedAt:"2026-09-26T12:00:01Z",subject:{type:"program",id:"Program111"}};response=await fetch(`${base}/api/monitor/evidence`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(evidence)});const evaluation=await response.json();assert.equal(evaluation[0].result.status,"breach");assert.equal((await(await fetch(`${base}/api/alerts`)).json()).length,1)}));

test("registry survives server recreation with the same database",async()=>{const directory=await import("node:fs/promises").then(({mkdtemp})=>mkdtemp("/tmp/alert-registry-"));const database=`${directory}/rules.sqlite`;const first=createAlertConsole({database});first.listen(0,"127.0.0.1");await once(first,"listening");const base=`http://127.0.0.1:${first.address().port}`;const rule={id:"persisted",version:1,name:"Persisted",cluster:"devnet",field:"nav",operator:"greater_than",threshold:1,severity:"high",recommendedAction:"Review."};await fetch(`${base}/api/rules`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rule})});first.close();await once(first,"close");const second=createAlertConsole({database});second.listen(0,"127.0.0.1");await once(second,"listening");const rules=await(await fetch(`http://127.0.0.1:${second.address().port}/api/rules`)).json();assert.equal(rules[0].rule.id,"persisted");second.close();await once(second,"close")});
