let mode="";let selected=null;let alerts=[];let rules=[];const list=document.querySelector("#alerts");const detail=document.querySelector("#detail");const ruleList=document.querySelector("#rules");
function esc(value){return String(value??"—").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]))}
function counts(){for(const state of ["open","acknowledged","resolved"])document.querySelector(`#${state==="acknowledged"?"ack":state}-count`).textContent=alerts.filter(a=>a.lifecycle===state).length;document.querySelector("#breach-count").textContent=alerts.filter(a=>a.status==="breach").length}
function renderList(){counts();if(!alerts.length){list.innerHTML='<p class="empty">No alerts match this view.</p>';return}list.innerHTML=alerts.map(a=>`<button class="alert ${a.id===selected?"selected":""}" data-id="${esc(a.id)}"><div class="alert-top"><span><span class="mode ${esc(a.mode)}">${esc(a.mode)}</span> <span class="severity ${esc(a.severity)}">${esc(a.severity)}</span></span><span class="state">${esc(a.lifecycle)}</span></div><h3>${esc(a.ruleId)}</h3><div class="meta">${esc(a.subject.type)} ${esc(a.subject.id)} · ${a.occurrences} occurrence${a.occurrences===1?"":"s"}</div></button>`).join("");list.querySelectorAll("[data-id]").forEach(button=>button.addEventListener("click",()=>{selected=button.dataset.id;renderList();renderDetail()}))}
function renderDetail(){const a=alerts.find(x=>x.id===selected);if(!a){detail.innerHTML='<p class="step">EVIDENCE DETAIL</p><h2>Select an alert</h2><p>Source, rule version, slot/time, uncertainty, evidence IDs, and recommended action appear here.</p>';return}detail.innerHTML=`<p class="step">EVIDENCE DETAIL</p><h2>${esc(a.ruleId)}</h2><p>${esc(a.recommendedAction)}</p>${a.solanaMeaning?`<section class="meaning"><strong>What this represents on Solana</strong><p>${esc(a.solanaMeaning)}</p></section>`:""}<dl><div><dt>Mode / lifecycle</dt><dd>${esc(a.mode)} / ${esc(a.lifecycle)}</dd></div><div><dt>Rule</dt><dd>${esc(a.ruleId)} v${esc(a.ruleVersion)}</dd></div><div><dt>Subject</dt><dd>${esc(a.subject.type)} ${esc(a.subject.id)}</dd></div><div><dt>Source / slot</dt><dd>${esc(a.source?.id)} / ${esc(a.slot)}</dd></div><div><dt>Uncertainty</dt><dd>${esc(a.uncertainty)}</dd></div><div><dt>Evidence IDs</dt><dd>${a.evidenceIds.map(esc).join("<br>")}</dd></div><div><dt>First / last seen</dt><dd>${esc(a.firstSeenAt)}<br>${esc(a.lastSeenAt)}</dd></div></dl>${["open","acknowledged"].includes(a.lifecycle)?`<div class="actions">${a.lifecycle==="open"?'<button class="ack">Acknowledge</button>':""}<button class="resolve">Resolve</button></div>`:""}`;detail.querySelector(".ack")?.addEventListener("click",()=>act(a.id,"acknowledge",{actor:"local-analyst"}));detail.querySelector(".resolve")?.addEventListener("click",()=>act(a.id,"resolve",{resolution:"manually_resolved"}))}
function renderRules(){if(!rules.length){ruleList.innerHTML='<p class="empty">No rules published.</p>';return}ruleList.innerHTML=rules.map(item=>`<label class="rule"><input type="checkbox" data-rule-id="${esc(item.id)}" data-version="${item.version}"><span><strong>${esc(item.rule.name)}</strong><small>${esc(item.id)} v${item.version} · ${esc(item.rule.operator)} ${esc(item.rule.threshold)}</small></span><span class="state">${esc(item.activation)}</span></label>`).join("")}
async function loadRules(){rules=await(await fetch("/api/rules")).json();renderRules()}
async function changeRules(action){const selectedRules=[...ruleList.querySelectorAll("input:checked")].map(input=>({id:input.dataset.ruleId,version:Number(input.dataset.version)}));if(!selectedRules.length)return;await fetch(`/api/rules/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rules:selectedRules,actor:"local-analyst"})});await loadRules()}
async function act(id,action,body){await fetch(`/api/alerts/${encodeURIComponent(id)}/${action}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});await load()}
async function activateDemo(name){await fetch(`/api/demo/activate/${encodeURIComponent(name)}`,{method:"POST"});mode="fixture_simulation";document.querySelectorAll("[data-mode]").forEach(x=>x.classList.toggle("active",x.dataset.mode===mode));await load()}
async function clearDemo(){await fetch("/api/demo/clear",{method:"POST"});selected=null;await load()}
async function load(){const lifecycle=document.querySelector("#lifecycle").value;const params=new URLSearchParams();if(mode)params.set("mode",mode);if(lifecycle)params.set("lifecycle",lifecycle);alerts=await(await fetch(`/api/alerts?${params}`)).json();renderList();renderDetail()}
document.querySelectorAll("[data-mode]").forEach(button=>button.addEventListener("click",()=>{mode=button.dataset.mode;document.querySelectorAll("[data-mode]").forEach(x=>x.classList.toggle("active",x===button));load()}));document.querySelector("#lifecycle").addEventListener("change",load);
document.querySelector("#activate-rules").addEventListener("click",()=>changeRules("activate"));document.querySelector("#pause-rules").addEventListener("click",()=>changeRules("pause"));document.querySelectorAll("[data-demo]").forEach(button=>button.addEventListener("click",()=>activateDemo(button.dataset.demo)));document.querySelector("#clear-demo").addEventListener("click",clearDemo);fetch("/api/health").then(r=>r.json()).then(()=>{const h=document.querySelector("#health");h.textContent="ACTIVE";h.classList.add("active")});const stream=new EventSource("/api/stream");stream.addEventListener("alert",load);load();loadRules();
