import test from "node:test";
import assert from "node:assert/strict";
import { once } from "node:events";
import { createDemoServer } from "./server.js";
import { evidenceFor } from "./client.js";

function fakeChain(){let index=0;return{programId:"ProgramDevnet",mint:"MintDevnet",payerPubkey:"KnownAuthority1111111111111111111111111111",treasuryTokenPubkey:"TreasuryToken111111111111111111111111111",async walletActivity({publicKey}){const signatures=["wallet-real","fund-real","deposit-real","arm-real","trigger-session-1","evac-real"];return{publicKey,transactions:signatures.map((signature,slot)=>({signature,slot:slot+1,blockTime:900+slot,status:"confirmed",explorer:`https://explorer.test/${signature}`}))}},async fundBurner({recipientPubkey}){return{publicKey:recipientPubkey,balanceSol:0.08,balanceUsdc:1000,signature:"fund-real"}},async initialize({ttlSeconds,ownerPubkey}){index++;return{sessionId:`session-${index}`,sessionPda:`pda-${index}`,ownerPubkey,signature:`init-${index}`,expiresAt:new Date(Date.now()+ttlSeconds*1000).toISOString()}},async prepareDeposit({sessionPda,ownerPubkey,amount}){return{transaction:"unsigned-deposit",positionPda:`position-${ownerPubkey}`,amount,sessionPda}},async submitDeposit({signedTransaction}){assert.equal(signedTransaction,"signed-deposit");return{signature:"deposit-real",slot:7,positionPda:"position-owner",amount:500}},async prepareProtection(){return{armTransaction:"unsigned-arm",permitTransaction:"partial-durable-nonce",noncePubkey:"nonce-real",fee:5}},async submitProtection({signedArmTransaction,signedPermitTransaction}){assert.equal(signedArmTransaction,"signed-arm");assert.equal(signedPermitTransaction,"signed-permit");return{signature:"arm-real",noncePubkey:"nonce-real",permitTransaction:"signed-permit"}},async trigger({sessionId,flags}){return{sessionId,flags,signature:`trigger-${sessionId}`}},async executeEvacuation({signedTransaction}){assert.equal(signedTransaction,"signed-permit");return{signature:"evac-real",slot:9,amount:495,fee:5}},async reset({sessionId}){return{sessionId,flags:0,signature:`reset-${sessionId}`}}}}
async function withServer(fn){const server=createDemoServer({chain:fakeChain(),clock:()=>1000});server.listen(0,"127.0.0.1");await once(server,"listening");try{await fn(`http://127.0.0.1:${server.address().port}`)}finally{server.close();await once(server,"close")}}

test("serves a concise self-explanatory Saturn-to-Kelvara journey",async()=>withServer(async base=>{const health=await(await fetch(`${base}/api/health`)).json();assert.equal(health.service,"devnet-scenario-capsule");const html=await(await fetch(base)).text();assert.match(html,/5-minute walkthrough/);assert.match(html,/Five guided steps/);assert.match(html,/one-time.*burner wallet/s);assert.match(html,/Saturn USDC Earn/);assert.match(html,/NEW/);assert.match(html,/One signature/);assert.match(html,/SATURN EARN · POSITION/);assert.match(html,/Optional protection/);assert.match(html,/Activate protection/);assert.match(html,/STEP 4 · MONITORING/);assert.match(html,/A new authority can control the vault/);assert.match(html,/Your protected funds.*are back/s);const icon=await fetch(`${base}/saturn-mark.svg`);assert.equal(icon.status,200);assert.match(icon.headers.get("content-type"),/image\/svg\+xml/)}));

test("serves distinct portfolio tabs and immediate wallet restart",async()=>withServer(async base=>{const html=await(await fetch(base)).text();for(const view of ["overview","positions","rules","activity"]){assert.match(html,new RegExp(`data-view="${view}"`));assert.match(html,new RegExp(`data-view-panel="${view}"`))}assert.equal((html.match(/data-position-record/g)||[]).length,1);assert.match(html,/Portfolio value/);assert.match(html,/Discovered positions/);assert.match(html,/Protection rules/);assert.match(html,/On-chain activity/);assert.match(html,/id="reset" class="quiet">Restart demo/);const css=await(await fetch(`${base}/styles.css`)).text();assert.match(css,/\.kelvara-view\{display:none/);assert.match(css,/\.kelvara-view\.active\{display:block/);const app=await(await fetch(`${base}/app.js`)).text();assert.match(app,/sendBeacon\(`\/api\/sessions\/\$\{session\.id\}\/reset`/);assert.match(app,/sessionStorage\.removeItem\("kelvara_demo_wallet"\);sessionStorage\.removeItem\("kelvara_access"\);location\.reload\(\)/)}));

test("serves a state-preserving Saturn and Kelvara app switcher",async()=>withServer(async base=>{const html=await(await fetch(base)).text();assert.match(html,/class="app-switcher"/);assert.match(html,/data-app="saturn"/);assert.match(html,/data-app="kelvara"[^>]*disabled/);assert.match(html,/switch-lock/);assert.match(html,/progress-rail/);assert.match(html,/hero-visual/);assert.match(html,/Saturn Earn/);assert.match(html,/Kelvara/);const app=await(await fetch(`${base}/app.js`)).text();assert.match(app,/lastSaturnStage/);assert.match(app,/lastKelvaraStage/);assert.match(app,/switchMiniApp/);assert.match(app,/--progress/)}));

test("shows burner-wallet identity, expiry recovery, and transparent full-principal protection",async()=>withServer(async base=>{const html=await(await fetch(base)).text();assert.match(html,/THIRD-PARTY SOLANA WALLET/);assert.match(html,/SATURN EARN · POSITION/);assert.match(html,/class="protection-recommendation"/);assert.match(html,/Activate protection/);assert.match(html,/id="stage-protection-review"/);assert.match(html,/12 months or until you revoke it/);assert.match(html,/Return transaction amount/);assert.doesNotMatch(html,/Guaranteed return amount/);assert.match(html,/Monitored authority address/);assert.match(html,/id="rule-authority"/);assert.match(html,/id="incident-time"/);assert.match(html,/id="incident-hash"/);assert.match(html,/Team did not announce the authority change/);assert.doesNotMatch(html,/742\.50/);const app=await(await fetch(`${base}/app.js`)).text();assert.match(app,/Blockhash expired/);assert.match(app,/Back and regenerate transaction/);assert.match(app,/regenerateProtection/);assert.match(app,/kelvara_access/);assert.match(app,/Sign 2 Solana transactions/);assert.match(app,/Network<\/span><b>Devnet/);assert.doesNotMatch(app,/Guaranteed return amount/);assert.match(app,/protectedPrincipal=depositAmount/);assert.match(app,/protection-review/);assert.match(app,/prepared\.treasuryExplorer/);assert.match(app,/treasuryAddress/);assert.match(app,/sendBeacon/);assert.doesNotMatch(app,/await post\(`\/api\/sessions\/\$\{session\.id\}\/reset/)}));

test("returns chain-fetched wallet activity and authority pubkeys",async()=>withServer(async base=>{let response=await fetch(`${base}/api/wallets/Owner111111111111111111111111111111111/activity`);assert.equal(response.status,200);const activity=await response.json();assert.equal(activity.transactions[0].signature,"wallet-real");response=await fetch(`${base}/api/sessions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ttlSeconds:120,ownerPubkey:"Owner111111111111111111111111111111111"})});const session=await response.json();response=await fetch(`${base}/api/sessions/${session.id}/trigger`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scenarios:["authority_changed"],idempotencyKey:"authority-proof"})});const breach=await response.json();assert.equal(breach.authorities.before,"KnownAuthority1111111111111111111111111111");assert.equal(breach.authorities.now,session.sessionPda)}));

test("creates isolated session and supports idempotent scenario trigger",async()=>withServer(async base=>{let response=await fetch(`${base}/api/sessions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ttlSeconds:120})});assert.equal(response.status,201);const session=await response.json();assert.equal(session.status,"created");const input={scenarios:["paused","nav_jump"],idempotencyKey:"same-action"};response=await fetch(`${base}/api/sessions/${session.id}/trigger`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});const first=await response.json();response=await fetch(`${base}/api/sessions/${session.id}/trigger`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});const second=await response.json();assert.deepEqual(second,first);assert.equal(first.flags,3)}));

test("restores the same wallet capsule and isolates different wallets behind one IP",async()=>withServer(async base=>{const create=ownerPubkey=>fetch(`${base}/api/sessions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ttlSeconds:60,ownerPubkey})});const firstResponse=await create("WalletA");assert.equal(firstResponse.status,201);const first=await firstResponse.json();const retryResponse=await create("WalletA");assert.equal(retryResponse.status,200);const restored=await retryResponse.json();assert.equal(restored.id,first.id);assert.equal(restored.restored,true);const secondResponse=await create("WalletB");assert.equal(secondResponse.status,201);const second=await secondResponse.json();assert.notEqual(second.id,first.id);const reset=await(await fetch(`${base}/api/sessions/${first.id}/reset`,{method:"POST"})).json();assert.equal(reset.status,"baseline");assert.equal((await create("WalletA")).status,201)}));

test("rejects unsupported scenarios and missing idempotency key",async()=>withServer(async base=>{const session=await(await fetch(`${base}/api/sessions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ttlSeconds:60})})).json();let response=await fetch(`${base}/api/sessions/${session.id}/trigger`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scenarios:["shell"],idempotencyKey:"x"})});assert.equal(response.status,400);response=await fetch(`${base}/api/sessions/${session.id}/trigger`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scenarios:["paused"]})});assert.equal(response.status,400)}));

test("publishes confirmed trigger and reset evidence to Alert Console",async()=>{const posted=[];const monitor={async publish(evidence){posted.push(evidence);return[{ruleId:"pause",result:{status:evidence.value.paused?"breach":"pass"}}]}};const server=createDemoServer({chain:fakeChain(),monitor});server.listen(0,"127.0.0.1");await once(server,"listening");try{const base=`http://127.0.0.1:${server.address().port}`;const session=await(await fetch(`${base}/api/sessions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ttlSeconds:60})})).json();const result=await(await fetch(`${base}/api/sessions/${session.id}/trigger`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scenarios:["paused"],idempotencyKey:"monitor-1"})})).json();assert.equal(result.monitoring[0].result.status,"breach");const reset=await(await fetch(`${base}/api/sessions/${session.id}/reset`,{method:"POST"})).json();assert.equal(posted.length,2);assert.equal(posted[0].cluster,"devnet");assert.equal(posted[0].source.type,"monitoring_backend");assert.equal(posted[1].value.scenarioFlags,0);assert.equal(reset.monitoring[0].result.status,"pass")}finally{server.close();await once(server,"close")}});

test("TTL scheduler submits an automatic reset transaction",async()=>{let scheduled;const posted=[];const monitor={async publish(evidence){posted.push(evidence);return[]}};const server=createDemoServer({chain:fakeChain(),monitor,schedule(fn,ms){scheduled={fn,ms};return{unref(){}}}});server.listen(0,"127.0.0.1");await once(server,"listening");try{const base=`http://127.0.0.1:${server.address().port}`;await fetch(`${base}/api/sessions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ttlSeconds:30})});assert.equal(scheduled.ms,30000);await scheduled.fn();assert.equal(posted.length,1);assert.equal(posted[0].value.scenarioFlags,0);assert.match(posted[0].source.transactionSignature,/reset-/);assert.equal((await fetch(`${base}/api/sessions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ttlSeconds:30})})).status,201)}finally{server.close();await once(server,"close")}});

test("requires real browser signatures for deposit and durable-nonce protection",async()=>withServer(async base=>{
 const funded=await(await fetch(`${base}/api/sandbox/fund`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({publicKey:"Owner111"})})).json();assert.equal(funded.balanceUsdc,1000);
 const session=await(await fetch(`${base}/api/sessions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ttlSeconds:120,ownerPubkey:"Owner111"})})).json();
 let response=await fetch(`${base}/api/sessions/${session.id}/deposit/prepare`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount:500})});const prepared=await response.json();assert.equal(prepared.transaction,"unsigned-deposit");
 response=await fetch(`${base}/api/sessions/${session.id}/deposit/submit`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({signedTransaction:"signed-deposit"})});assert.equal(response.status,200);
 const protection=await(await fetch(`${base}/api/sessions/${session.id}/protection/prepare`,{method:"POST"})).json();assert.equal(protection.noncePubkey,"nonce-real");assert.equal(protection.treasuryAddress,"TreasuryToken111111111111111111111111111");assert.match(protection.treasuryExplorer,/address\/TreasuryToken/);
 response=await fetch(`${base}/api/sessions/${session.id}/protection/submit`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({signedArmTransaction:"signed-arm",signedPermitTransaction:"signed-permit"})});assert.equal(response.status,200);
 const trigger=await(await fetch(`${base}/api/sessions/${session.id}/trigger`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({scenarios:["authority_changed"],idempotencyKey:"real-flow"})})).json();assert.equal(trigger.evacuation.signature,"evac-real");assert.equal(trigger.evacuation.amount,500);
 const activity=await(await fetch(`${base}/api/wallets/Owner111/activity`)).json();const bySignature=Object.fromEntries(activity.transactions.map(tx=>[tx.signature,tx]));assert.equal(bySignature["fund-real"].action,"Wallet funded");assert.equal(bySignature["deposit-real"].protocol,"Saturn Earn");assert.equal(bySignature["arm-real"].action,"Protection fee paid");assert.equal(bySignature["arm-real"].amount,5);assert.equal(bySignature["evac-real"].action,"Emergency evacuation");assert.equal(bySignature["evac-real"].amount,500);assert.equal(bySignature["wallet-real"].action,"Solana transaction");
}));

test("refuses protection without deposit or an unprepared submit",async()=>withServer(async base=>{const session=await(await fetch(`${base}/api/sessions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ttlSeconds:60,ownerPubkey:"Owner111"})})).json();assert.equal((await fetch(`${base}/api/sessions/${session.id}/protection/prepare`,{method:"POST"})).status,409);assert.equal((await fetch(`${base}/api/sessions/${session.id}/deposit/submit`,{method:"POST",headers:{"content-type":"application/json"},body:"{}"})).status,409)}));
