import { readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { resolve } from "node:path";
import anchor from "@coral-xyz/anchor";
import { Connection, Keypair, PublicKey, SystemProgram, Transaction, sendAndConfirmTransaction, NONCE_ACCOUNT_LENGTH } from "@solana/web3.js";
import { ASSOCIATED_TOKEN_PROGRAM_ID, TOKEN_PROGRAM_ID, createAssociatedTokenAccountInstruction, createInitializeMintInstruction, createMintToInstruction, getAssociatedTokenAddressSync, getMint, getAccount, MINT_SIZE } from "@solana/spl-token";
import { makeSessionId, PROGRAM_ID, signatureFromConfirmationError } from "./client.js";

function configuredPath(name){const value=process.env[name];if(!value)throw new TypeError(`${name} is required`);return value.startsWith("~/")?resolve(homedir(),value.slice(2)):resolve(value)}
async function loadKeypair(path){return Keypair.fromSecretKey(Uint8Array.from(JSON.parse(await readFile(path,"utf8"))))}
async function confirmedFingerprint(connection,signature){for(let attempt=0;attempt<18;attempt++){const transaction=await connection.getTransaction(signature,{commitment:"confirmed",maxSupportedTransactionVersion:0});if(transaction?.slot){const blockTime=transaction.blockTime??Math.floor(Date.now()/1000);return{signature,slot:transaction.slot,observedAt:new Date(blockTime*1000).toISOString()}}await new Promise(resolve=>setTimeout(resolve,1000))}throw new Error("confirmed_transaction_unavailable")}
async function sendAndConfirm(connection,send){try{return await confirmedFingerprint(connection,await send())}catch(error){const signature=signatureFromConfirmationError(error);if(!signature)throw error;return confirmedFingerprint(connection,signature)}}
function encode(transaction){return transaction.serialize({requireAllSignatures:false,verifySignatures:false}).toString("base64")}
function decode(value){return Transaction.from(Buffer.from(value,"base64"))}

export async function createChainAdapter(){
 const connection=new Connection(process.env.DEVNET_RPC_URL||"https://api.devnet.solana.com","confirmed");const payer=await loadKeypair(configuredPath("DEVNET_SPONSOR_KEYPAIR"));const mintKeypair=await loadKeypair(configuredPath("DEVNET_USDC_MINT_KEYPAIR"));const wallet=new anchor.Wallet(payer);const provider=new anchor.AnchorProvider(connection,wallet,{commitment:"confirmed",preflightCommitment:"confirmed"});const idl=JSON.parse(await readFile(new URL("./target/idl/scenario_capsule.json",import.meta.url),"utf8"));const programId=new PublicKey(PROGRAM_ID);idl.address=PROGRAM_ID;const program=new anchor.Program(idl,provider);const mint=mintKeypair.publicKey;const treasuryToken=getAssociatedTokenAddressSync(mint,payer.publicKey);
 function pda(sessionId){return PublicKey.findProgramAddressSync([Buffer.from("demo-session"),payer.publicKey.toBuffer(),Buffer.from(sessionId)],programId)[0]}
 function positionPda(sessionPda,owner){return PublicKey.findProgramAddressSync([Buffer.from("position"),new PublicKey(sessionPda).toBuffer(),new PublicKey(owner).toBuffer()],programId)[0]}
 async function ensureMint(){try{await getMint(connection,mint)}catch{const rent=await connection.getMinimumBalanceForRentExemption(MINT_SIZE);const tx=new Transaction().add(SystemProgram.createAccount({fromPubkey:payer.publicKey,newAccountPubkey:mint,space:MINT_SIZE,lamports:rent,programId:TOKEN_PROGRAM_ID}),createInitializeMintInstruction(mint,6,payer.publicKey,null));await sendAndConfirmTransaction(connection,tx,[payer,mintKeypair])}try{await getAccount(connection,treasuryToken)}catch{await sendAndConfirmTransaction(connection,new Transaction().add(createAssociatedTokenAccountInstruction(payer.publicKey,treasuryToken,payer.publicKey,mint)),[payer])}}
 await ensureMint();
 async function initialize({ttlSeconds,ownerPubkey}){if(!ownerPubkey)throw new TypeError("owner_pubkey_required");const sessionId=makeSessionId();const sessionPda=pda(sessionId);const fingerprint=await sendAndConfirm(connection,()=>program.methods.initializeSession([...sessionId],new anchor.BN(ttlSeconds)).accounts({session:sessionPda,authority:payer.publicKey,systemProgram:SystemProgram.programId}).rpc());const account=await program.account.demoSession.fetch(sessionPda);return{sessionId:sessionId.toString("hex"),sessionPda:sessionPda.toBase58(),ownerPubkey,expiresAt:new Date(account.expiresAt.toNumber()*1000).toISOString(),...fingerprint}}
 async function trigger({sessionPda,flags}){const fingerprint=await sendAndConfirm(connection,()=>program.methods.triggerScenarios(flags).accounts({session:new PublicKey(sessionPda),authority:payer.publicKey}).rpc());return{sessionPda,flags,...fingerprint}}
 async function reset({sessionPda}){const fingerprint=await sendAndConfirm(connection,()=>program.methods.resetSession().accounts({session:new PublicKey(sessionPda),authority:payer.publicKey}).rpc());return{sessionPda,flags:0,...fingerprint}}
 async function fundBurner({recipientPubkey}){const owner=new PublicKey(recipientPubkey);const ownerToken=getAssociatedTokenAddressSync(mint,owner);const tx=new Transaction();const balance=await connection.getBalance(owner);if(balance<80_000_000)tx.add(SystemProgram.transfer({fromPubkey:payer.publicKey,toPubkey:owner,lamports:80_000_000-balance}));let tokenBalance=0;try{tokenBalance=Number((await getAccount(connection,ownerToken)).amount)/1e6}catch{tx.add(createAssociatedTokenAccountInstruction(payer.publicKey,ownerToken,owner,mint))}if(tokenBalance<1000)tx.add(createMintToInstruction(mint,ownerToken,payer.publicKey,Math.round((1000-tokenBalance)*1e6)));if(!tx.instructions.length)return{publicKey:recipientPubkey,balanceSol:balance/1e9,balanceUsdc:tokenBalance,signature:"already_funded",mint:mint.toBase58(),tokenAccount:ownerToken.toBase58()};const signature=await sendAndConfirmTransaction(connection,tx,[payer],{commitment:"confirmed"});await confirmedFingerprint(connection,signature);return{publicKey:recipientPubkey,balanceSol:(await connection.getBalance(owner))/1e9,balanceUsdc:Number((await getAccount(connection,ownerToken)).amount)/1e6,signature,mint:mint.toBase58(),tokenAccount:ownerToken.toBase58()}}
 async function prepareDeposit({sessionPda,ownerPubkey,amount}){const owner=new PublicKey(ownerPubkey);const position=positionPda(sessionPda,owner);const ownerToken=getAssociatedTokenAddressSync(mint,owner);const vaultToken=getAssociatedTokenAddressSync(mint,position,true);const transaction=await program.methods.depositPosition(new anchor.BN(Math.round(amount*1e6))).accounts({session:new PublicKey(sessionPda),position,owner,mint,ownerToken,vaultToken,tokenProgram:TOKEN_PROGRAM_ID,associatedTokenProgram:ASSOCIATED_TOKEN_PROGRAM_ID,systemProgram:SystemProgram.programId}).transaction();transaction.feePayer=owner;transaction.recentBlockhash=(await connection.getLatestBlockhash("confirmed")).blockhash;return{transaction:encode(transaction),positionPda:position.toBase58(),vaultToken:vaultToken.toBase58(),amount}}
 async function submitDeposit({signedTransaction,positionPda,amount}){const signature=await connection.sendRawTransaction(decode(signedTransaction).serialize(),{skipPreflight:false});return{...await confirmedFingerprint(connection,signature),positionPda,amount}}
 async function prepareProtection({sessionPda,positionPda:positionAddress,ownerPubkey,amount}){const owner=new PublicKey(ownerPubkey);const position=new PublicKey(positionAddress);const nonce=Keypair.generate();const rent=await connection.getMinimumBalanceForRentExemption(NONCE_ACCOUNT_LENGTH);const nonceCreate=new Transaction().add(SystemProgram.createNonceAccount({fromPubkey:payer.publicKey,noncePubkey:nonce.publicKey,authorizedPubkey:owner,lamports:rent}));const nonceSignature=await sendAndConfirmTransaction(connection,nonceCreate,[payer,nonce],{commitment:"confirmed"});await confirmedFingerprint(connection,nonceSignature);const nonceValue=(await connection.getNonce(nonce.publicKey,"confirmed"))?.nonce;if(!nonceValue)throw new Error("nonce_account_unavailable");const ownerToken=getAssociatedTokenAddressSync(mint,owner);const vaultToken=getAssociatedTokenAddressSync(mint,position,true);const armIx=await program.methods.armProtection().accounts({session:new PublicKey(sessionPda),position,owner,mint,ownerToken,treasuryToken,tokenProgram:TOKEN_PROGRAM_ID}).instruction();const arm=new Transaction({feePayer:payer.publicKey,recentBlockhash:(await connection.getLatestBlockhash("confirmed")).blockhash}).add(armIx);arm.partialSign(payer);const evacIx=await program.methods.evacuate().accounts({session:new PublicKey(sessionPda),position,owner,mint,vaultToken,ownerToken,tokenProgram:TOKEN_PROGRAM_ID}).instruction();const permit=new Transaction({feePayer:payer.publicKey,recentBlockhash:nonceValue,nonceInfo:{nonce:nonceValue,nonceInstruction:SystemProgram.nonceAdvance({noncePubkey:nonce.publicKey,authorizedPubkey:owner})}}).add(evacIx);permit.partialSign(payer);return{armTransaction:encode(arm),permitTransaction:encode(permit),noncePubkey:nonce.publicKey.toBase58(),nonceCreateSignature:nonceSignature,fee:amount*0.01}}
 async function submitProtection({signedArmTransaction,signedPermitTransaction,noncePubkey}){const signature=await connection.sendRawTransaction(decode(signedArmTransaction).serialize(),{skipPreflight:false});const fingerprint=await confirmedFingerprint(connection,signature);return{...fingerprint,noncePubkey,permitTransaction:signedPermitTransaction}}
 async function executeEvacuation({signedTransaction}){const signature=await connection.sendRawTransaction(decode(signedTransaction).serialize(),{skipPreflight:false});return{...await confirmedFingerprint(connection,signature),evacuated:true}}
 async function walletActivity({publicKey,limit=5}){const address=new PublicKey(publicKey);const signatures=await connection.getSignaturesForAddress(address,{limit:Math.min(5,Math.max(1,Number(limit)||5))},"confirmed");return{publicKey:address.toBase58(),transactions:signatures.map(item=>({signature:item.signature,slot:item.slot,blockTime:item.blockTime,status:item.err?"failed":"confirmed",explorer:`https://explorer.solana.com/tx/${item.signature}?cluster=devnet`}))}}
 return{programId:PROGRAM_ID,mint:mint.toBase58(),payerPubkey:payer.publicKey.toBase58(),treasuryTokenPubkey:treasuryToken.toBase58(),initialize,trigger,reset,fundBurner,prepareDeposit,submitDeposit,prepareProtection,submitProtection,executeEvacuation,walletActivity};
}
