import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { resolveKaminoRuntimeConfig, loadOrCreateProtectionKey } from "../subapps/kamino-monitor/runtime-config.js";

test("HAOS runtime binds externally and stores protection state under /data", () => {
  const config = resolveKaminoRuntimeConfig({ HOST: "0.0.0.0", PORT: "7650", KELVARA_RUNTIME_DIR: "/data/kamino-monitor" });
  assert.equal(config.host, "0.0.0.0"); assert.equal(config.port, 7650); assert.equal(config.keyPath, "/data/kamino-monitor/protection.key"); assert.equal(config.storePath, "/data/kamino-monitor/armed-protection.enc");
});
test("local runtime keeps loopback and repository-local state defaults", () => { const config = resolveKaminoRuntimeConfig({}, "/opt/kelvara/subapps/kamino-monitor"); assert.equal(config.host, "127.0.0.1"); assert.equal(config.port, 8080); assert.equal(config.runtimeDir, "/opt/kelvara/.runtime/kamino-monitor"); });
test("invalid bind ports are rejected", () => { assert.throws(() => resolveKaminoRuntimeConfig({ PORT: "0" }), /PORT/); assert.throws(() => resolveKaminoRuntimeConfig({ PORT: "not-a-port" }), /PORT/); });
test("production internal tokens must be distinct", () => { const env = { NODE_ENV: "production", HOST: "0.0.0.0", KELVARA_CONTROL_PLANE_URL: "http://control", KELVARA_OBSERVATION_HUB_URL: "http://observation", KELVARA_CONTROL_PLANE_TOKEN: "x".repeat(32), KELVARA_OBSERVATION_HUB_TOKEN: "x".repeat(32), GOVERNANCE_CURSOR_SECRET: "s".repeat(32) }; assert.throws(() => resolveKaminoRuntimeConfig(env), /distinct/); });
test("governance Hub config and stable cursor secret are exposed", () => { const env = { KELVARA_GOVERNANCE_HUB_URL: "http://governance", KELVARA_GOVERNANCE_HUB_TOKEN: "g".repeat(32), GOVERNANCE_CURSOR_SECRET: "s".repeat(32) }; const config = resolveKaminoRuntimeConfig(env); assert.equal(config.governanceHubUrl, "http://governance"); assert.equal(config.governanceHubToken, "g".repeat(32)); assert.equal(config.governanceCursorSecret, "s".repeat(32)); });
test("production governance cursor secret is required", () => { assert.throws(() => resolveKaminoRuntimeConfig({ NODE_ENV: "production", KELVARA_GOVERNANCE_HUB_URL: "http://governance", KELVARA_GOVERNANCE_HUB_TOKEN: "g".repeat(32) }), /GOVERNANCE_CURSOR_SECRET/); });
test("protection key is created once with restrictive permissions", async () => { const dir = await mkdtemp(join(tmpdir(), "kelvara-key-")); try { const keyPath = join(dir, "protection.key"), storePath = join(dir, "armed-protection.enc"), key = await loadOrCreateProtectionKey({ keyPath, storePath }); assert.equal(key.length, 32); assert.equal((await readFile(keyPath, "utf8")).trim(), key.toString("base64")); } finally { await rm(dir, { recursive: true, force: true }); } });
test("existing encrypted state without its key fails closed", async () => { const dir = await mkdtemp(join(tmpdir(), "kelvara-key-")); try { const keyPath = join(dir, "protection.key"), storePath = join(dir, "armed-protection.enc"); await writeFile(storePath, "ciphertext"); await assert.rejects(loadOrCreateProtectionKey({ keyPath, storePath }), /protection_key_missing_for_existing_store/); } finally { await rm(dir, { recursive: true, force: true }); } });
test("corrupt protection key fails closed", async () => { const dir = await mkdtemp(join(tmpdir(), "kelvara-key-")); try { const keyPath = join(dir, "protection.key"), storePath = join(dir, "armed-protection.enc"); await writeFile(keyPath, "not-base64", { mode: 0o600 }); await assert.rejects(loadOrCreateProtectionKey({ keyPath, storePath }), /protection_key_invalid/); } finally { await rm(dir, { recursive: true, force: true }); } });
