const FIXTURE_HOLDER='4g7kC6haaE6MzUx428DRdfrgHmwo7Sj5XYAqkx4ys3Rt';
const MAINNET_EXAMPLE='9GEMGj45WgCHZ6d7em4K1drmwSjJU3v5CZQ8dLhFnHYM';
const form=document.querySelector('#inspect-form');const input=document.querySelector('#wallet');const network=document.querySelector('#cluster');const submit=document.querySelector('#inspect-button');const status=document.querySelector('#status');const results=document.querySelector('#results');let latest=null;
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]);
const fact=(label,value)=>`<li><span>${esc(label)}</span><span>${esc(value)}</span></li>`;
function message(text,error=false){status.textContent=text;status.className=`status${error?' error':''}`}
function hideMessage(){status.className='hidden'}
function render(data){latest=data;const position=data.discovery.positions?.[0];const assurance=data.assurance?.assurance;if(!position){results.innerHTML=`<article class="result"><h2>No monitored ONYC position</h2><p class="muted">No positive exact-mint match on ${esc(data.network||data.cluster)}.</p></article>`}else{const simulated=data.mode==='fixture_simulation';const resolved=data.discovery.inputType==='token_account'?`Token account resolved to owner ${data.wallet}`:'Connected/public wallet';results.innerHTML=`<article class="result found"><span class="badge">${esc(simulated?'devnet-fixture · fixture simulation':data.cluster)}</span><h2>ONYC position found</h2><div class="amount">${esc(position.amount)} ONYC</div><p class="muted">${esc(resolved)}</p><ul class="facts">${fact('Owner wallet',data.wallet)}${fact('Mint',position.mint)}${fact('Raw amount',position.rawAmount)}${fact('RPC evidence',data.discovery.sourceStatus)}${simulated?fact('Evidence mode','fixture_simulation · not chain data'):''}${fact('ONRE controls',assurance?.sourceStatus||`unavailable: ${data.assuranceError||'not configured'}`)}${fact('Observed',assurance?.observedAt||data.inspectedAt)}</ul></article><button class="export" id="export">Export JSON</button>`;document.querySelector('#export').onclick=exportJson}results.className='results'}
function exportJson(){const blob=new Blob([JSON.stringify(latest,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`kelvara-${latest.network||latest.cluster}-${latest.wallet}.json`;a.click();URL.revokeObjectURL(a.href)}
async function inspect(){const address=input.value.trim();if(!address)return message('Connect or paste a Solana address.',true);submit.disabled=true;results.className='hidden';message(`Finding position on ${network.value}…`);try{const response=await fetch(`/api/inspect/${encodeURIComponent(address)}?cluster=${encodeURIComponent(network.value)}`);const data=await response.json();if(!response.ok)throw new Error(data.error||'inspection_failed');hideMessage();render(data)}catch(error){message(error.message==='invalid_wallet'?'Invalid Solana address.':`Inspection failed: ${error.message}`,true)}finally{submit.disabled=false}}
async function loadServices(){try{const data=await(await fetch('/api/services')).json();document.querySelector('#services').innerHTML=Object.values(data).map(item=>`<span class="service ${esc(item.status)}">${esc(item.name)} · ${esc(item.status)}</span>`).join('')}catch{document.querySelector('#services').innerHTML='<span class="service unreachable">backend status unavailable</span>'}}
async function loadAlerts(){const box=document.querySelector('#alerts');try{const response=await fetch('/api/alerts');if(!response.ok)throw new Error();const alerts=await response.json();box.innerHTML=alerts.length?alerts.map(a=>`<article class="alert"><strong>${esc(a.ruleId)}</strong><div class="alert-meta">${esc(a.severity)} · ${esc(a.lifecycle)} · ${esc(a.subject?.id)}</div>${a.solanaMeaning?`<p><b>What this represents on Solana:</b> ${esc(a.solanaMeaning)}</p>`:''}</article>`).join(''):'<p class="empty">No fixture alerts.</p>'}catch{box.innerHTML='<p class="empty">Alert Console unavailable.</p>'}}
function connectFixture(){network.value='devnet-fixture';input.value=FIXTURE_HOLDER;document.querySelector('#wallet-state').textContent='Fixture wallet connected';document.querySelector('#wallet-detail').textContent=FIXTURE_HOLDER;inspect()}
form.onsubmit=event=>{event.preventDefault();inspect()};network.onchange=()=>{results.className='hidden';hideMessage()};document.querySelector('#connect-wallet').onclick=connectFixture;document.querySelector('#fixture-button').onclick=connectFixture;document.querySelector('#example-button').onclick=()=>{network.value='mainnet';input.value=MAINNET_EXAMPLE;inspect()};document.querySelector('#refresh').onclick=()=>Promise.all([loadServices(),loadAlerts()]);
await Promise.all([loadServices(),loadAlerts()]);setInterval(()=>Promise.all([loadServices(),loadAlerts()]),5000);
