const form=document.querySelector("#rule-form");
let paperCluster="devnet";
const paperBox=document.querySelector("#paper-evidence");
const devnetBox=document.querySelector("#devnet-evidence");
const paperSample={id:"paper:nav:1",cluster:"devnet",state:"active",freshness:{status:"fresh",ageMs:1000,maxAgeMs:15000},confidence:"verified",coverage:"complete",value:{nav:1.02,previousNav:1,disagreement:false}};
const devnetSample={id:"devnet:nav:1",cluster:"devnet",source:{id:"monitoring-backend-devnet",type:"monitoring_backend"},slot:123456,observedAt:"2026-09-26T10:00:00.000Z",fetchedAt:"2026-09-26T10:00:01.000Z",state:"active",freshness:{status:"fresh",ageMs:1000,maxAgeMs:15000},confidence:"verified",coverage:"complete",value:{nav:1.06,previousNav:1,disagreement:false}};
paperBox.value=JSON.stringify(paperSample,null,2);devnetBox.value=JSON.stringify(devnetSample,null,2);
function threshold(value,operator){if(operator==="equals"&&Number.isNaN(Number(value)))return value;if(operator==="source_disagreement")return value==="true";return Number(value)}
function rule(cluster="devnet"){const data=new FormData(form);const operator=data.get("operator");return{id:"rule-studio",version:1,name:data.get("name"),cluster,field:data.get("field"),operator,threshold:threshold(data.get("threshold"),operator),nearThresholdPercent:Number(data.get("near")),severity:"high",recommendedAction:data.get("action"),...(operator==="percent_change_greater_than"?{previousField:"previousNav"}:{})}}
function updateSummary(){const r=rule();const words={greater_than:"is greater than",less_than:"is less than",equals:"differs from",percent_change_greater_than:"changes by more than",freshness_greater_than:"age is greater than",source_disagreement:"reports disagreement equal to"};document.querySelector("#summary").textContent=`Breach when ${r.field} ${words[r.operator]} ${r.threshold}. Review within ${r.nearThresholdPercent}% of threshold.`}form.addEventListener("input",updateSummary);updateSummary();
function render(id,payload){const card=document.querySelector(`#${id}-result`);const result=payload.result;const badge=card.querySelector(".badge");badge.textContent=result.status.toUpperCase();badge.className=`badge ${result.status}`;card.querySelector("h3").textContent={pass:"Condition not met",review:"Near threshold",breach:"Rule breached",unknown:"Evidence insufficient"}[result.status];card.querySelector(".reason").textContent=result.status==="unknown"?result.reason:result.recommendedAction;const provenance=payload.provenance?`<br>source ${payload.provenance.source.id}<br>slot ${payload.provenance.slot}<br>observed ${payload.provenance.observedAt}`:"fixture evidence";card.querySelector(".facts").innerHTML=`network ${result.cluster??"devnet"}<br>actual ${result.actual??"—"}<br>threshold ${result.threshold??"—"}<br>${provenance}`}
async function evaluate(level,box,url){const card=document.querySelector(`#${level}-result`);try{const evidence=JSON.parse(box.value);const selectedCluster=level==="paper"?paperCluster:"devnet";const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rule:rule(selectedCluster),evidence})});const payload=await response.json();if(!response.ok)throw new Error(`${payload.error}: ${(payload.errors??[]).join(", ")}`);render(level,payload)}catch(error){const badge=card.querySelector(".badge");badge.textContent="ERROR";badge.className="badge breach";card.querySelector("h3").textContent="Cannot evaluate";card.querySelector(".reason").textContent=error.message}}
document.querySelectorAll("[data-paper-cluster]").forEach(button=>button.addEventListener("click",()=>{paperCluster=button.dataset.paperCluster;document.querySelectorAll("[data-paper-cluster]").forEach(item=>item.classList.toggle("active",item===button));try{const value=JSON.parse(paperBox.value);value.cluster=paperCluster;paperBox.value=JSON.stringify(value,null,2)}catch{}}));
document.querySelector("#paper-run").addEventListener("click",()=>evaluate("paper",paperBox,"/api/preview"));document.querySelector("#devnet-run").addEventListener("click",()=>evaluate("devnet",devnetBox,"/api/levels/devnet/evaluate"));
async function refresh(){try{const levels=await(await fetch("/api/levels")).json();for(const level of ["paper","devnet"]){const value=levels[level];if(value?.result)render(level,value)}const runs=[levels.paper,levels.devnet].filter(value=>value?.counts).map(value=>`${value.level}: ${value.total} total · ${value.counts.breach} breach · ${value.counts.unknown} unknown`);document.querySelector("#run-counts").textContent=runs.join(" | ")||"No published batch runs."}catch{}}refresh();setInterval(refresh,3000);
