const $=selector=>document.querySelector(selector);
const UNKNOWN="Unknown";let token="",refreshing=false;
function text(id,value){const node=$(id);if(node)node.textContent=value??UNKNOWN}
function known(v){return v!==null&&v!==undefined&&v!==""}
function number(v){return known(v)&&Number.isFinite(Number(v))?new Intl.NumberFormat().format(Number(v)):UNKNOWN}
function duration(s){if(!known(s)||!Number.isFinite(Number(s)))return UNKNOWN;let n=Math.max(0,Math.floor(Number(s))),d=Math.floor(n/86400);n%=86400;const h=Math.floor(n/3600);n%=3600;const m=Math.floor(n/60),p=[];if(d)p.push(`${d}d`);if(h||d)p.push(`${h}h`);p.push(`${m}m`);return p.join(" ")}
function milliseconds(v){return known(v)&&Number.isFinite(Number(v))?`${new Intl.NumberFormat(undefined,{maximumFractionDigits:0}).format(Number(v))} ms`:UNKNOWN}
function bytes(v){if(!known(v)||!Number.isFinite(Number(v)))return UNKNOWN;const u=["B","KB","MB","GB","TB"];let n=Number(v),i=0;while(Math.abs(n)>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`}
function ratio(v){return known(v)&&Number.isFinite(Number(v))?`${(Number(v)*100).toFixed(1)}%`:UNKNOWN}
function iso(v){if(!known(v))return UNKNOWN;const d=new Date(typeof v==="number"&&v<1e12?v*1000:v);return Number.isNaN(d.valueOf())?UNKNOWN:d.toLocaleString()}
function label(v){return known(v)?String(v).replaceAll("_"," "):UNKNOWN}function safe(v){return String(v??"")}
async function request(path,authenticated=false,options={}){const headers={accept:"application/json",...(options.headers||{})};if(authenticated&&token)headers.Authorization=`Bearer ${token}`;const response=await fetch(path,{cache:"no-store",...options,headers});let body={};try{body=await response.json()}catch{}if(!response.ok)throw Object.assign(new Error(body.error||`http_${response.status}`),{status:response.status,path});return body}
function renderSource(source){text("#source-freshness",label(source?.freshness?.status));text("#source-access",source?.access?`${source.access} source`:UNKNOWN);text("#source-head",source?.head?.blockTime?`Head ${iso(source.head.blockTime)}`:"No indexed head");text("#source-signatures",number(source?.counts?.signatures));text("#source-processed",number(source?.counts?.processed));text("#source-pending",number(source?.counts?.pending));text("#source-failed",number(source?.counts?.failed));text("#source-instructions",number(source?.counts?.rawInstructions));text("#source-accounts",number(source?.counts?.rawAccounts));const schema=source?.schema;text("#source-schema",schema?schema.compatible?"Compatible":`Incompatible · ${(schema.problems||[]).join(" · ")||"problem reported"}`:UNKNOWN)}
function renderStatus(status){text("#service-state",label(status?.service?.state));text("#service-stage",status?.service?.stage?`Stage: ${label(status.service.stage)}`:status?.service?.cycle?`Cycle: ${status.service.cycle}`:"No active invariant scan");text("#service-uptime",duration(status?.service?.uptimeSeconds));text("#source-lag",milliseconds(status?.kpis?.sourceLagMs));text("#processing-lag",milliseconds(status?.kpis?.processingLagMs));text("#operations-backlog",number(status?.kpis?.backlog));text("#provider-state",label(status?.providers?.state));text("#provider-count",known(status?.providers?.providerCount)?`${number(status.providers.providerCount)} observed providers`:"No provider samples");text("#provider-latency",milliseconds(status?.kpis?.providerLatencyMs));text("#provider-success",ratio(status?.providers?.recentWindow?.successRatio??status?.kpis?.observationSuccessRatio));text("#provider-samples",number(status?.providers?.recentWindow?.sampleCount));const storage=status?.storage||{};text("#storage-action",label(storage.action));text("#storage-used",known(storage.utilization)?`${ratio(storage.utilization)} of ${bytes(storage.maxBytes)} quota`:"Quota not measured");text("#storage-db-size",bytes(storage.dbBytes));text("#storage-free",bytes(storage.remainingBytes));const retention=status?.retention||{};text("#retention-state",label(retention.state));text("#compaction-lag",duration(retention.compactionLagSeconds));renderIncidents(status?.incidents||[])}
function renderIndexers(payload){const list=$("#indexer-list"),items=payload?.indexers||[];list.replaceChildren();if(!items.length){list.innerHTML='<p class="empty">No protocol indexers returned.</p>';return}for(const item of items){const card=document.createElement("article");card.className="indexer-card";const counts=item.counts||{};card.innerHTML=`<div><strong>${safe(item.name||item.protocol)}</strong><small>${safe(item.network)} · ${safe(item.sourceType)}</small></div><span class="chip ${safe(item.freshness?.status)}">${safe(label(item.freshness?.status))}</span><dl><div><dt>Signatures</dt><dd>${number(counts.signatures)}</dd></div><div><dt>Processed</dt><dd>${number(counts.processed)}</dd></div><div><dt>Pending</dt><dd>${number(counts.pending)}</dd></div></dl>`;list.append(card)}}
function renderHistory(payload){const states={gap:"gap",adverse:"adverse",healthy:"healthy"};const chart=$("#continuity-chart");chart.replaceChildren();for(const hour of payload?.hours||[]){const state=states[hour.state]||states.gap;const bar=document.createElement("span");bar.className=`continuity-bar ${state}`;bar.title=`${iso(hour.bucketStart)} · ${state} · ${hour.sampleCount} samples`;bar.setAttribute("aria-label",bar.title);chart.append(bar)}const providers=$("#provider-list");providers.replaceChildren();for(const provider of payload?.providers||[]){const chip=document.createElement("span");chip.className="chip";chip.textContent=provider==="helius"?"Helius":provider==="solana-public-rpc"?"Solana public RPC":provider;providers.append(chip)}if(!providers.children.length)providers.innerHTML='<span class="chip">No provider samples</span>'}
function renderTargets(payload){const c=payload?.coverage||{};text("#coverage-targets",number(c.uniqueTargets));text("#coverage-positions",number(c.distinctWallets));text("#coverage-links",number(c.walletTargetLinks));const body=$("#target-table-body"),targets=payload?.targets||[];body.replaceChildren();if(!targets.length){body.innerHTML='<p class="empty">No target records returned.</p>';return}for(const target of targets){const row=document.createElement("div");row.className="target-row";row.innerHTML=`<code>${safe(target.address||target.id)}</code><span>${safe(label(target.protocol))}</span><span>${number(target.walletCount)}</span>`;body.append(row)}}
function paidAmount(client){return client.paidAmount??(client.paymentCount?"Recorded in detail":"No payment records")}
function renderClients(payload){const body=$("#client-table-body"),clients=payload?.clients||[];body.replaceChildren();if(!clients.length){body.innerHTML='<p class="empty">No enrolled clients returned.</p>';return}for(const client of clients){const row=document.createElement("button");row.type="button";row.className="target-row client-row";row.innerHTML=`<code>${safe(client.walletId)}</code><span>${iso(client.lastActivityAt)}</span><span>${safe(paidAmount(client))}</span><span>${number(client.evacuationCount)}</span>`;row.onclick=()=>loadClient(client.walletId);body.append(row)}}
function detailRows(node,items,empty,render){node.replaceChildren();if(!items.length){node.innerHTML=`<p class="empty">${safe(empty)}</p>`;return}for(const item of items){const row=document.createElement("article");row.className="incident";row.innerHTML=render(item);node.append(row)}}
async function loadClient(walletId){const detail=$("#client-detail"),evacuations=$("#client-evacuations"),payments=$("#client-payments");detail.innerHTML='<p class="empty">Loading client data…</p>';try{const client=await request(`/api/operations/clients/${encodeURIComponent(walletId)}`,true);detail.innerHTML=`<p class="eyebrow">CLIENT WALLET</p><h3>${safe(client.walletId)}</h3><div class="detail-row"><span>Status</span><strong>${safe(label(client.status))}</strong></div><div class="detail-row"><span>Enrolled</span><strong>${iso(client.enrolledAt)}</strong></div><div class="detail-row"><span>Last activity</span><strong>${iso(client.lastActivityAt)}</strong></div><div class="detail-row"><span>Activity records</span><strong>${number(client.activity.length)}</strong></div>`;detailRows(evacuations,client.evacuationTransactions||[],"No signed evacuation transactions recorded.",item=>`<span class="severity">${safe(label(item.status))}</span><div><strong>${safe(item.signature)}</strong><small>Evacuation transaction fingerprint</small></div><time>${iso(item.observedAt)}</time>`);detailRows(payments,client.payments||[],"No payment records in SQL.",item=>`<span class="severity">${safe(label(item.status))}</span><div><strong>${safe(item.amount)} ${safe(item.asset)}</strong><small>${safe(item.signature||"No transaction signature recorded")}</small></div><time>${iso(item.paidAt)}</time>`)}catch(error){detail.innerHTML=`<p class="empty">${safe(error.message)}</p>`}}
function renderSettings(settings){$("#quota-gb").value=settings?.evidenceQuotaGb??50}
function renderIncidents(items){const list=$("#incident-list");list.replaceChildren();text("#incident-count",number(items.length));if(!items.length){list.innerHTML='<p class="empty">No incidents returned.</p>';return}for(const item of items){const row=document.createElement("article");row.className="incident";row.innerHTML=`<span class="severity">${safe(label(item.severity??item.kind??"incident"))}</span><div><strong>${safe(item.message??item.reason??item.type??"Operational incident")}</strong><small>${safe(item.stage?`Stage: ${item.stage}`:item.resolvedAt?"Resolved":"Persisted evidence")}</small></div><time>${iso(item.occurredAt??item.createdAt??item.startedAt)}</time>`;list.append(row)}}
async function refresh(){if(refreshing)return;refreshing=true;$("#refresh").disabled=true;const paths=["/api/health","/api/sources/onre-indexer","/api/operations/status","/api/operations/targets","/api/operations/indexers","/api/operations/history?hours=24","/api/operations/settings","/api/operations/clients"];const results=await Promise.allSettled(paths.map((path,index)=>request(path,index>1)));const [health,source,status,targets,indexers,history,settings,clients]=results;const ok=health.status==="fulfilled"&&health.value.ok;let authFailed=results.some(r=>r.status==="rejected"&&r.reason?.status===401);if(source.status==="fulfilled")renderSource(source.value);if(status.status==="fulfilled")renderStatus(status.value);if(targets.status==="fulfilled")renderTargets(targets.value);if(indexers.status==="fulfilled")renderIndexers(indexers.value);if(history.status==="fulfilled")renderHistory(history.value);if(settings.status==="fulfilled")renderSettings(settings.value);if(clients.status==="fulfilled")renderClients(clients.value);const state=$("#connection-state"),complete=results.every(r=>r.status==="fulfilled");state.className=`status ${ok?(complete?"available":"degraded"):"unavailable"}`;state.innerHTML=`<i></i>${ok?authFailed?"Admin token required":complete?"Live":"Partially available":"API unavailable"}`;text("#notice",authFailed?"Admin APIs require a token. It remains in this page memory only.":ok&&!complete?"Some evidence is unavailable. Gaps and unknowns remain explicit.":ok?"Unknown means not measured. It never means zero or healthy.":"Monitoring control-plane API unavailable.");text("#last-refresh",new Date().toLocaleTimeString());$("#refresh").disabled=false;refreshing=false}
const panes=new Set(["overview","incidents","indexers","providers","targets","clients","continuity","storage"]);
function showPane(name){const pane=panes.has(name)?name:"overview";document.querySelectorAll("[data-view]").forEach(node=>node.classList.toggle("hidden",node.dataset.view!==pane));let active;document.querySelectorAll("[data-pane]").forEach(node=>{node.classList.toggle("active",node.dataset.pane===pane);if(node.dataset.pane===pane)active=node});if(innerWidth<=720)requestAnimationFrame(()=>active?.scrollIntoView({block:"nearest",inline:"center"}));if(location.hash!==`#monitoring/${pane}`)history.replaceState(null,"",`#monitoring/${pane}`)}
function showWorkspace(name){const admin=name==="admin";$("#monitoring-shell").classList.toggle("hidden",admin);$("#admin-shell").classList.toggle("hidden",!admin);$("#monitoring-tab").classList.toggle("active",!admin);$("#admin-tab").classList.toggle("active",admin);$("#monitoring-tab").setAttribute("aria-selected",String(!admin));$("#admin-tab").setAttribute("aria-selected",String(admin));if(admin)history.replaceState(null,"","#admin")}
document.querySelectorAll("[data-pane]").forEach(node=>node.onclick=()=>{showWorkspace("monitoring");showPane(node.dataset.pane)});$("#monitoring-tab").onclick=()=>{showWorkspace("monitoring");showPane("overview")};$("#admin-tab").onclick=()=>showWorkspace("admin");const initial=location.hash.slice(1);if(initial==="admin")showWorkspace("admin");else{showWorkspace("monitoring");showPane(initial.startsWith("monitoring/")?initial.split("/")[1]:"overview")}$("#refresh").onclick=refresh;$("#apply-token").onclick=()=>{token=$("#operations-token").value.trim();$("#operations-token").value="";refresh()};$("#operations-token").onkeydown=e=>{if(e.key==="Enter")$("#apply-token").click()};$("#save-quota").onclick=async()=>{const value=Number($("#quota-gb").value);try{const result=await request("/api/operations/settings",true,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({evidenceQuotaGb:value})});renderSettings(result);text("#quota-message",`Saved ${result.evidenceQuotaGb} GB. Maintenance uses it immediately.`);refresh()}catch(error){text("#quota-message",error.message)}};
refresh();setInterval(refresh,15000);
