import { createHmac, timingSafeEqual } from "node:crypto";
import { validateSolanaAddress } from "../../src/domains/discovery/wallet.js";

const NETWORKS = new Set(["mainnet-beta"]);
const MAX_LIMIT = 100, MAX_WALLETS = 16, MAX_VAULTS = 32, MAX_ITEMS = 100, MAX_STRING = 512, MAX_DEPTH = 8;
const SENSITIVE = /rawbytes|signedtransaction|secret|token|private|seed|mnemonic|credential|password|permit|enrollment/i;
const sets = {
  top: new Set(["schemaVersion","network","freshness","wallets","warnings"]), freshness: new Set(["state","observedAt","finalizedSlot"]),
  wallet: new Set(["address","vaults"]), vault: new Set(["identity","membership","requiresAttention","currentActions","recentChanges","nextHistoryCursor"]),
  identity: new Set(["provider","generation","multisigAddress","vaultIndex","vaultAddress"]), membership: new Set(["role","permissions","threshold","memberCount"]),
  action: new Set(["id","status","decodedIntent","approvalProgress","userStatus","proposer","createdSlot","finalizedSlot","sourceSignature","instructions","provenance","unresolvedInstructionCount"]),
  intent: new Set(["summary","kind"]), approval: new Set(["approved","rejected","threshold"]), instruction: new Set(["index","programId","accounts","rawData","intent","decoder","unresolved","provenance"]), provenance: new Set(["decoderFamily","decoderVersion","artifactHash","transactionAddress","accountAddress","staticAccountIndexes"]),
};
function fail() { throw new Error("observation_hub_malformed"); }
function obj(value, allowed, depth) { if (!value || typeof value !== "object" || Array.isArray(value) || depth > MAX_DEPTH) fail(); for (const key of Object.keys(value)) if (SENSITIVE.test(key) || !allowed.has(key)) fail(); return value; }
function str(value) { if (typeof value !== "string" || value.length > MAX_STRING || /[\u0000-\u001f\u007f]/.test(value)) fail(); return value; }
function integer(value, min = 0, max = Number.MAX_SAFE_INTEGER) { if (!Number.isSafeInteger(value) || value < min || value > max) fail(); return value; }
function address(value) { str(value); if (!validateSolanaAddress(value)) fail(); return value; }
function action(value, depth) { const x=obj(value,sets.action,depth); const intent=obj(x.decodedIntent,sets.intent,depth+1), approval=obj(x.approvalProgress,sets.approval,depth+1), provenance=obj(x.provenance,sets.provenance,depth+1); const instructions=Array.isArray(x.instructions)&&x.instructions.length<=MAX_ITEMS?x.instructions.map(i=>{const q=obj(i,sets.instruction,depth+1); const ip=obj(q.provenance,sets.provenance,depth+2); return {index:integer(q.index),programId:address(q.programId),accounts:Array.isArray(q.accounts)&&q.accounts.length<=MAX_ITEMS?q.accounts.map(address):fail(),rawData:Array.isArray(q.rawData)&&q.rawData.length<=16384&&q.rawData.every(b=>Number.isInteger(b)&&b>=0&&b<=255)?q.rawData:fail(),intent:obj(q.intent,new Set(["kind"]),depth+2),decoder:obj(q.decoder,new Set(["family","version","artifactHash"]),depth+2),unresolved:q.unresolved===true,provenance:{transactionAddress:address(ip.transactionAddress),accountAddress:address(ip.accountAddress),staticAccountIndexes:Array.isArray(ip.staticAccountIndexes)?ip.staticAccountIndexes.map(integer):fail()}};}):fail(); return {id:str(x.id),status:str(x.status),decodedIntent:{summary:str(intent.summary),kind:str(intent.kind)},approvalProgress:{approved:integer(approval.approved),rejected:integer(approval.rejected),threshold:integer(approval.threshold,1)},userStatus:str(x.userStatus),proposer:x.proposer===null?null:address(x.proposer),createdSlot:x.createdSlot===null?null:integer(x.createdSlot),finalizedSlot:x.finalizedSlot===null?null:integer(x.finalizedSlot),sourceSignature:x.sourceSignature===null?null:str(x.sourceSignature),instructions,provenance:{decoderFamily:str(provenance.decoderFamily),decoderVersion:str(provenance.decoderVersion),artifactHash:str(provenance.artifactHash)},unresolvedInstructionCount:integer(x.unresolvedInstructionCount)}; }
function vault(value, depth) { const x=obj(value,sets.vault,depth), i=obj(x.identity,sets.identity,depth+1), m=obj(x.membership,sets.membership,depth+1); if (!Array.isArray(m.permissions)||m.permissions.length>MAX_ITEMS||m.threshold<1||m.threshold>m.memberCount) fail(); return {identity:{provider:str(i.provider),generation:str(i.generation),multisigAddress:address(i.multisigAddress),vaultIndex:integer(i.vaultIndex),vaultAddress:address(i.vaultAddress)},membership:{role:str(m.role),permissions:m.permissions.map(str),threshold:integer(m.threshold,1),memberCount:integer(m.memberCount,1)},requiresAttention:Array.isArray(x.requiresAttention)?x.requiresAttention.map(a=>action(a,depth+1)):fail(),currentActions:Array.isArray(x.currentActions)?x.currentActions.map(a=>action(a,depth+1)):fail(),recentChanges:Array.isArray(x.recentChanges)?x.recentChanges.map(a=>action(a,depth+1)):fail(),nextHistoryCursor:x.nextHistoryCursor===null?null:str(x.nextHistoryCursor)}; }
function canonical(wallet, network, value) { const x=obj(value,sets.top,0); if(x.schemaVersion!=="observation-hub-governance/v1"||x.network!==network) fail(); const f=obj(x.freshness,sets.freshness,1); if(!["fresh","stale","partial","unknown"].includes(f.state)||(f.observedAt!==null&&(typeof f.observedAt!=="string"||Number.isNaN(Date.parse(f.observedAt))))||(f.finalizedSlot!==null&&integer(f.finalizedSlot)<0))fail(); if(!Array.isArray(x.wallets)||x.wallets.length!==1||x.wallets.length>MAX_WALLETS)fail(); const w=obj(x.wallets[0],sets.wallet,1); if(w.address!==wallet||!Array.isArray(w.vaults)||w.vaults.length>MAX_VAULTS)fail(); if(x.warnings!==undefined&&(!Array.isArray(x.warnings)||x.warnings.length>MAX_ITEMS))fail(); return {schemaVersion:x.schemaVersion,network,freshness:{state:f.state,observedAt:f.observedAt===null?null:str(f.observedAt),finalizedSlot:f.finalizedSlot===null?null:integer(f.finalizedSlot)},wallets:[{address:wallet,vaults:w.vaults.map(v=>vault(v,2))}],warnings:(x.warnings||[]).map(str).slice(0,20)}; }
export function createGovernanceClient({url,token,fetchImpl=fetch}={}) { if(!url||!token)throw new Error("governance_client_config_missing"); return async request=>{let response;try{response=await fetchImpl(new URL("/internal/v1/governance/actions/query",url),{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify(request),signal:AbortSignal.timeout(2000)});}catch{throw new Error("observation_hub_unavailable");}if(!response.ok)throw new Error("observation_hub_unavailable");try{return await response.json();}catch{throw new Error("observation_hub_malformed");}}; }
function sign(cursor,wallet,network,secret){const payload=Buffer.from(JSON.stringify({cursor,wallet,network})).toString("base64url");return `${payload}.${createHmac("sha256",secret).update(payload).digest("base64url")}`;}
function read(value,wallet,network,secret){if(!value)return null;const [payload,sig]=String(value).split("."), expected=payload&&createHmac("sha256",secret).update(payload).digest("base64url");if(!payload||!sig||sig.length!==expected.length||!timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))throw new Error("invalid_cursor");let x;try{x=JSON.parse(Buffer.from(payload,"base64url"));}catch{throw new Error("invalid_cursor");}if(x.wallet!==wallet||x.network!==network||typeof x.cursor!=="string"||x.cursor.length>MAX_STRING)throw new Error("invalid_cursor");return x.cursor;}
export function createGovernanceHandler({query,cursorSecret}){if(!cursorSecret||Buffer.from(cursorSecret).length<32)throw new Error("governance_cursor_secret_required");return async({wallet,network,historyLimit,cursor})=>{const upstream=read(cursor,wallet,network,cursorSecret);try{const result=canonical(wallet,network,await query({chain:"solana",network,walletAddresses:[wallet],historyLimitPerVault:historyLimit,historyCursor:upstream}));for(const v of result.wallets[0].vaults)if(v.nextHistoryCursor)v.nextHistoryCursor=sign(v.nextHistoryCursor,wallet,network,cursorSecret);return result;}catch(error){if(error.message==="invalid_cursor")throw error; throw new Error("governance_unavailable");}};}
export function parseGovernanceQuery(url){const network=url.searchParams.get("network");if(!NETWORKS.has(network))throw new Error("invalid_network");for(const key of ["wallet","walletAddresses"])if(url.searchParams.has(key))throw new Error("wallet_query_not_allowed");const raw=url.searchParams.get("history_limit"),historyLimit=raw===null?10:Number(raw);if(!Number.isInteger(historyLimit)||historyLimit<1||historyLimit>MAX_LIMIT)throw new Error("invalid_history_limit");return{network,historyLimit,cursor:url.searchParams.get("cursor")};}
