const API_BASE=location.hostname==="kelvara.xyz"||location.hostname==="www.kelvara.xyz"?"https://demo-api.kelvara.xyz":"";function apiUrl(path){return `${API_BASE}${path}`}
const $=selector=>document.querySelector(selector);const web3=window.solanaWeb3;
let wallet,session,balance={sol:0,usdc:0},depositAmount=0,protectedPrincipal=0,pendingSign=null,pendingProtection=null,sse=null,incidentResult=null;
let lastSaturnStage="wallet",lastKelvaraStage="kelvara";
const stages=["wallet","earn","naked","kelvara","protection-review","monitor","incident","breach"];
const saturnStages=new Set(["wallet","earn","naked"]),kelvaraStages=new Set(["kelvara","protection-review","monitor","incident","breach"]);
function short(value){return value?`${value.slice(0,4)}…${value.slice(-4)}`:"—"}
function toBase64(bytes){let binary="";for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary)}
function fromBase64(value){const binary=atob(value);return Uint8Array.from(binary,c=>c.charCodeAt(0))}
async function request(path,options={}){const response=await fetch(apiUrl(path),options);const value=await response.json();if(!response.ok)throw new Error(value.message||value.error||"Request failed");return value}
function post(path,value={}){return request(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(value)})}
function explorer(signature){return `https://explorer.solana.com/tx/${signature}?cluster=devnet`}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2400)}
function setStage(name){for(const stage of stages)$(`#stage-${stage}`)?.classList.toggle("active",stage===name);if(saturnStages.has(name))lastSaturnStage=name;if(kelvaraStages.has(name))lastKelvaraStage=name;document.querySelectorAll(".app-switch").forEach(button=>button.classList.toggle("active",button.dataset.app===(saturnStages.has(name)?"saturn":"kelvara")));const map={wallet:0,earn:1,naked:1,kelvara:2,"protection-review":2,monitor:3,incident:3,breach:4};const step=map[name]??0;document.querySelector(".journey").style.setProperty("--progress",`${step*25}%`);document.querySelectorAll(".journey-step").forEach((el,index)=>{el.classList.toggle("active",index===step);el.classList.toggle("done",index<step);el.querySelector("em").textContent=index<step?"✓":String(index+1)});window.scrollTo({top:0,behavior:"smooth"})}
function switchMiniApp(app){setStage(app==="saturn"?lastSaturnStage:lastKelvaraStage)}
document.querySelectorAll(".app-switch").forEach(button=>button.onclick=()=>switchMiniApp(button.dataset.app));
function updateWallet(){const address=wallet.publicKey.toBase58();$("#wallet-address").textContent=address;$("#chip-address").textContent=short(address);$("#saturn-address").textContent=short(address);$("#kelvara-address").textContent=short(address);$("#position-owner").textContent=short(address);$("#sol-balance").textContent=`${balance.sol.toFixed(3)} SOL`;$("#usdc-balance").textContent=`${balance.usdc.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} USDC`;$("#available-usdc").textContent=`${balance.usdc.toFixed(2)} USDC`;$("#wallet-chip").disabled=false}
function transactionFrom(value){return web3.Transaction.from(fromBase64(value))}
function signTransaction(value){const transaction=transactionFrom(value);transaction.partialSign(wallet);return toBase64(transaction.serialize({requireAllSignatures:false,verifySignatures:false}))}
function signerFacts(count=1){return `<div class="review-row"><span>Network</span><b>Devnet</b></div><div class="review-row"><span>Request</span><b>${count} Solana transaction${count===1?"":"s"}</b></div><div class="review-row"><span>Signer</span><code>${wallet.publicKey.toBase58()}</code></div><div class="review-block"><strong>No intent metadata</strong><p>This third-party wallet receives serialized Solana transaction bytes. Review product terms in the requesting app before signing.</p></div>`}
function openDrawer({title,html,label="Sign on Devnet",action}){const address=wallet?.publicKey.toBase58()||"";$("#drawer-wallet-id").textContent=address?`•••• ${address.slice(-8)}`:"Preparing…";$("#wallet-drawer h2").textContent=title;$("#drawer-body").innerHTML=html;$("#sign").textContent=label;pendingSign=action;$("#wallet-drawer").classList.add("open");$("#wallet-drawer").setAttribute("aria-hidden","false");$("#scrim").classList.add("open")}
function closeDrawer(){$("#wallet-drawer").classList.remove("open");$("#wallet-drawer").setAttribute("aria-hidden","true");$("#scrim").classList.remove("open");pendingSign=null}
function activityRows(transactions){return transactions.length?transactions.map(tx=>{const icon=tx.icon==="saturn"?"./saturn-mark.svg":tx.icon==="kelvara"?"./kelvara-icon.png":null;const iconHtml=icon?`<img class="activity-icon" src="${icon}" alt="${tx.protocol}">`:'<span class="activity-icon wallet-activity-icon">◎</span>';const amount=Number.isFinite(tx.amount)?`<b class="activity-amount">${tx.action.includes("fee")?"−":tx.action.includes("evacuation")?"+":""}${tx.amount.toFixed(2)} ${tx.asset||""}</b>`:`<b class="activity-status">${tx.status}</b>`;return `<a class="activity-row" href="${tx.explorer}" target="_blank" rel="noopener">${iconHtml}<span class="activity-copy"><strong>${tx.action}</strong><small>${tx.protocol} · ${short(tx.signature)} · ${tx.blockTime?new Date(tx.blockTime*1000).toLocaleString():`Slot ${tx.slot}`}</small></span>${amount}<span class="activity-link">↗</span></a>`}).join(""):"<p class=\"empty-activity\">No confirmed wallet transactions found yet.</p>"}
async function loadKelvaraActivity(){const source=$("#kelvara-activity-source"),list=$("#kelvara-activity-list");source.textContent="Loading from Solana…";list.innerHTML='<p class="empty-activity">Loading confirmed Devnet transactions…</p>';try{const activity=await request(`/api/wallets/${encodeURIComponent(wallet.publicKey.toBase58())}/activity`);source.textContent="Fetched from Solana RPC";list.innerHTML=activityRows(activity.transactions)}catch(error){source.textContent="Could not load activity";list.innerHTML=`<p class="empty-activity">${error.message}</p>`}}
function showKelvaraView(name){document.querySelectorAll(".kelvara-nav").forEach(button=>button.classList.toggle("selected",button.dataset.view===name));document.querySelectorAll(".kelvara-view").forEach(panel=>panel.classList.toggle("active",panel.dataset.viewPanel===name));$("#kelvara-view-title").textContent=name[0].toUpperCase()+name.slice(1);if(name==="activity")loadKelvaraActivity()}
document.querySelectorAll(".kelvara-nav").forEach(button=>button.onclick=()=>showKelvaraView(button.dataset.view));
document.querySelectorAll("[data-open-view]").forEach(button=>button.onclick=()=>showKelvaraView(button.dataset.openView));
$("#close-drawer").onclick=closeDrawer;$("#scrim").onclick=closeDrawer;$("#wallet-chip").onclick=()=>openDrawer({title:"Devnet burner wallet",label:"Close",html:`<div class="review-row"><span>Address</span><b>${short(wallet.publicKey.toBase58())}</b></div><div class="review-row"><span>SOL</span><b>${balance.sol.toFixed(3)}</b></div><div class="review-row"><span>Test USDC</span><b>${balance.usdc.toFixed(2)}</b></div><div class="review-block"><strong>Disposable Devnet wallet</strong><p>These tokens have no real-world value. Restarting creates a different wallet.</p></div>`,action:async()=>{}});
$("#kelvara-wallet-button").onclick=()=>$("#wallet-chip").click();
async function regenerateProtection(){pendingProtection=await post(`/api/sessions/${session.id}/protection/prepare`);populateProtectionReview(pendingProtection);setStage("protection-review");toast("Fresh transaction created")}
$("#sign").onclick=async()=>{if(!pendingSign)return closeDrawer();const button=$("#sign");button.disabled=true;const text=button.textContent;button.textContent="Confirming on Devnet…";try{await pendingSign();closeDrawer()}catch(error){const expired=/blockhash|block height exceeded|expired/i.test(error.message);if(expired&&pendingProtection){$("#wallet-drawer h2").textContent="Blockhash expired";$("#drawer-body").innerHTML='<div class="wallet-error"><strong>This transaction can no longer be submitted.</strong><p>Go back to Kelvara. A replacement transaction with a fresh blockhash will be created.</p></div>';button.textContent="Back and regenerate transaction";pendingSign=regenerateProtection}else if(expired){$("#wallet-drawer h2").textContent="Blockhash expired";$("#drawer-body").innerHTML='<div class="wallet-error"><strong>Transaction was not sent.</strong><p>Go back and create a fresh transaction.</p></div>';button.textContent="Close";pendingSign=null}else toast(error.message);console.error(error)}finally{button.disabled=false;if(pendingSign&&button.textContent!=="Back and regenerate transaction")button.textContent=text}};

async function init(){
 try{const stored=sessionStorage.getItem("kelvara_demo_wallet");wallet=stored?web3.Keypair.fromSecretKey(Uint8Array.from(JSON.parse(stored))):web3.Keypair.generate();if(!stored)sessionStorage.setItem("kelvara_demo_wallet",JSON.stringify([...wallet.secretKey]));
 const health=await request("/api/health");$("#health").classList.add("live");$("#health").innerHTML="<i></i> Devnet live";
 const funded=await post("/api/sandbox/fund",{publicKey:wallet.publicKey.toBase58()});balance.sol=funded.balanceSol;balance.usdc=funded.balanceUsdc;updateWallet();if(sessionStorage.getItem("kelvara_access")===wallet.publicKey.toBase58())$("[data-app=kelvara]").disabled=false;$("#position-wallet-address").textContent=short(wallet.publicKey.toBase58());$("#wallet-title").innerHTML="Your one-time burner wallet<br>is ready.";$("#wallet-lead").textContent="Use it throughout the walkthrough. These are simulated-value Devnet assets—not real money.";if(funded.explorer){$("#funding-proof").href=funded.explorer}else $("#funding-proof").remove();$("#continue").disabled=false;toast("Burner wallet ready");
 }catch(error){$("#health").textContent="Devnet unavailable";toast(error.message);console.error(error)}
}
$("#continue").onclick=()=>setStage("earn");$("#max").onclick=()=>{$("#deposit-amount").value=Math.floor(balance.usdc)};
$("#deposit").onclick=async()=>{depositAmount=Number($("#deposit-amount").value);if(!Number.isFinite(depositAmount)||depositAmount<=0||depositAmount>balance.usdc)return toast("Choose an amount within your test USDC balance");try{session=await post("/api/sessions",{ttlSeconds:300,ownerPubkey:wallet.publicKey.toBase58()});const monitoredAuthority=session.monitoredAuthority||"Unavailable";$("#rule-authority").textContent=monitoredAuthority;const prepared=await post(`/api/sessions/${session.id}/deposit/prepare`,{amount:depositAmount});openDrawer({title:"Transaction request",label:"Sign transaction",html:signerFacts(1),action:async()=>{const result=await post(`/api/sessions/${session.id}/deposit/submit`,{signedTransaction:signTransaction(prepared.transaction)});balance.usdc-=depositAmount;updateWallet();for(const id of ["position-value","portfolio-value","overview-position-value","overview-unprotected","position-view-amount"])$("#"+id).textContent=`${depositAmount.toFixed(2)}${id==="position-value"?"":" USDC"}`;$("#deposit-proof").href=result.explorer||explorer(result.signature);const kelvaraApp=$("[data-app=kelvara]");kelvaraApp.disabled=false;connectStream();setStage("naked")}})}catch(error){toast(error.message)}};
$("#open-kelvara").onclick=()=>{sessionStorage.setItem("kelvara_access",wallet.publicKey.toBase58());$("[data-app=kelvara]").disabled=false;showKelvaraView("overview");setStage("kelvara")};
$("#skip-protection").onclick=()=>{toast("Position remains in Saturn Earn")};
function populateProtectionReview(prepared){const address=wallet.publicKey.toBase58();$("#review-connected-wallet").textContent=address;$("#review-return-wallet").textContent=address;$("#review-protected-amount").textContent=`${depositAmount.toFixed(2)} USDC`;$("#review-return-amount").textContent=`${depositAmount.toFixed(2)} USDC`;$("#review-fee").textContent=`${prepared.fee.toFixed(2)} USDC`;$("#review-treasury").textContent=`${prepared.treasuryAddress} ↗`;$("#review-treasury").href=prepared.treasuryExplorer}
$("#activate").onclick=async()=>{try{pendingProtection=await post(`/api/sessions/${session.id}/protection/prepare`);protectedPrincipal=depositAmount;populateProtectionReview(pendingProtection);setStage("protection-review")}catch(error){toast(error.message)}};
$("#cancel-protection").onclick=()=>setStage("kelvara");
$("#continue-protection-signing").onclick=()=>{const prepared=pendingProtection;if(!prepared)return toast("Prepare protection first");openDrawer({title:"Transaction request",label:"Sign 2 Solana transactions",html:signerFacts(2),action:async()=>{await post(`/api/sessions/${session.id}/protection/submit`,{signedArmTransaction:signTransaction(prepared.armTransaction),signedPermitTransaction:signTransaction(prepared.permitTransaction)});balance.usdc-=prepared.fee;updateWallet();$("#protect-status").className="pill green";$("#protect-status").textContent="Protected";$("#position-view-status").className="pill green";$("#position-view-status").textContent="Protected";$("#overview-protected").textContent=`${protectedPrincipal.toFixed(2)} USDC`;$("#overview-unprotected").textContent="0.00 USDC";$("#protection-state-copy").textContent="Protection active";$("#activate").classList.add("hidden");$("#rules-count-state").className="pill green";$("#rules-count-state").textContent="Active";$("#rule-status").textContent="Monitoring";$("#protection-ready").classList.remove("hidden");pendingProtection=null;showKelvaraView("overview");setStage("kelvara");toast("Protection active")}})};
function connectStream(){if(sse)sse.close();sse=new EventSource(apiUrl(`/api/sessions/${session.id}/stream`));sse.onmessage=event=>{const data=JSON.parse(event.data);if(data.event==="attack_confirmed")toast(`Breach confirmed in slot ${data.slot}`);if(data.event==="evacuation_confirmed")toast("Emergency exit finalized")}};
$("#watch-position").onclick=()=>{$("#timeline-principal").textContent=`${protectedPrincipal.toFixed(2)} USDC`;$("#timeline-value").textContent=protectedPrincipal.toFixed(2);$("#timeline-yield").textContent="+0.00 USDC";setStage("monitor");runTimeline()};
async function runTimeline(){const duration=5000+Math.floor(Math.random()*5000);const ticks=Math.max(5,Math.floor(duration/700));let day=1;const interval=setInterval(()=>{day++;const simulatedYield=protectedPrincipal*(.072/365)*day;$("#timeline-day").textContent=`Day ${day}`;$("#timeline-value").textContent=(protectedPrincipal+simulatedYield).toFixed(2);$("#timeline-yield").textContent=`+${simulatedYield.toFixed(2)} USDC`;$("#growth-fill").style.width=`${Math.min(92,day/ticks*100)}%`;$("#timeline-check").textContent="All rules normal"},700);setTimeout(async()=>{clearInterval(interval);$("#timeline-check").textContent="Change detected";try{incidentResult=await post(`/api/sessions/${session.id}/trigger`,{scenarios:["authority_changed"],idempotencyKey:crypto.randomUUID()});if(!incidentResult.evacuation)throw new Error("Protection was not armed");balance.usdc+=protectedPrincipal;updateWallet();const knownAuthority=incidentResult.authorities?.before||"Unavailable",unexpectedAuthority=incidentResult.authorities?.now||"Unavailable";$("#known-authority").textContent=knownAuthority;$("#unexpected-authority").textContent=unexpectedAuthority;$("#incident-time").textContent=new Date(incidentResult.observedAt||Date.now()).toLocaleString();$("#incident-hash").textContent=incidentResult.signature;$("#incident-proof").href=explorer(incidentResult.signature);setStage("incident")}catch(error){toast(error.message)}},duration)}
$("#open-breach").onclick=()=>{if(!incidentResult)return;$("#secured-amount").textContent=`${protectedPrincipal.toFixed(2)} USDC`;$("#breach-signature").href=explorer(incidentResult.signature);$("#evacuation-signature").href=explorer(incidentResult.evacuation.signature);setStage("breach")};
$("#reveal-wallet").onclick=async()=>{const address=wallet.publicKey.toBase58();openDrawer({title:"Devnet burner wallet",label:"Close",html:`<div class="wallet-balance"><span>USDC balance</span><strong>${balance.usdc.toFixed(2)} USDC</strong><code>${address}</code></div><div class="activity-title"><strong>Recent Devnet transactions</strong><span>Loading from Solana…</span></div>`,action:async()=>{}});try{const activity=await request(`/api/wallets/${encodeURIComponent(address)}/activity`);$("#drawer-body").innerHTML=`<div class="wallet-balance"><span>USDC balance</span><strong>${balance.usdc.toFixed(2)} USDC</strong><code>${address}</code></div><div class="activity-title"><strong>Recent Devnet transactions</strong><span>Fetched from Solana RPC</span></div><div class="activity-list">${activityRows(activity.transactions)}</div>`}catch(error){$("#drawer-body .activity-title span").textContent="Could not load activity";toast(error.message)}};
$("#reset").onclick=()=>{if(session)navigator.sendBeacon(apiUrl(`/api/sessions/${session.id}/reset`));sessionStorage.removeItem("kelvara_demo_wallet");sessionStorage.removeItem("kelvara_access");location.reload()};
init();
